In [30]:
from collections import Counter
fname=input("Enter the file name: ")
count=0
my_list=[]
fhand=open(fname)
for line in fhand:
#         line=line.strip()
    if not line.startswith('From'):
        continue
#     count=count+1
    words=line.split()
    if len(words)==7:
#         print(words)
        my_list.append(int(words[-2].split(":")[0]))
 
my_list=dict(Counter(my_list))
sorted(my_list.keys())
for key in sorted(my_list.keys()) :
    print(key , my_list[key])

Enter the file name: mbox-short.txt
4 3
6 1
7 1
9 2
10 3
11 6
14 1
15 2
16 4
17 2
18 1
19 1


In [37]:
import re
hand=open('mbox-short.txt')
for line in hand:
    line=line.rstrip()
#     if re.search('^F..m',line):
#         print(line)
    x=re.findall('\S+@\S+',line)
    x=re.findall('^X\S*: ([0-9.]+)',line)
    if len(x)>0:
        print(x)

['0.8475']
['0.0000']
['0.6178']
['0.0000']
['0.6961']
['0.0000']
['0.7565']
['0.0000']
['0.7626']
['0.0000']
['0.7556']
['0.0000']
['0.7002']
['0.0000']
['0.7615']
['0.0000']
['0.7601']
['0.0000']
['0.7605']
['0.0000']
['0.6959']
['0.0000']
['0.7606']
['0.0000']
['0.7559']
['0.0000']
['0.7605']
['0.0000']
['0.6932']
['0.0000']
['0.7558']
['0.0000']
['0.6526']
['0.0000']
['0.6948']
['0.0000']
['0.6528']
['0.0000']
['0.7002']
['0.0000']
['0.7554']
['0.0000']
['0.6956']
['0.0000']
['0.6959']
['0.0000']
['0.7556']
['0.0000']
['0.9846']
['0.0000']
['0.8509']
['0.0000']
['0.9907']
['0.0000']


In [47]:
import re

# regexp = input('Enter a regular expression: ')
x=input('Enter a regular expression.')
file_name='mbox-short.txt'
file = open('mbox-short.txt')

count = 0
for line in file:
  line=line.rstrip()
  if re.search('\\b' + x + '\\b', line):
    count=count+1
print (f'{file_name} had {count} lines that matched {x}')

Enter a regular expression.java$
mbox-short.txt had 60 lines that matched java$


In [52]:
import re
count = 0
revisions = 0
x=input('Enter file:')
#Opening the file so that we can search through it
hand = open(x)
#Going through each line of the file to find all the instance of the words 'New Revision: 
#397*' After we've found this in the code, we're going to slice and extract the number.
#We'll count each instance and add each new found one to the next to make the sum
for line in hand:
    line = line.rstrip()
    if re.findall('New Revision: 397*', line):
      rev_num = line[14:19]
      count += 1
      revisions = revisions + float(rev_num)
#Using our count and sum from before, we can not calculate the average      
average = revisions/count
print(int(average))

Enter file:mbox-short.txt
39756


In [53]:

import string

counts = 0                          # Initialize variables
dictionary_counts = dict()
relative_lst = list()

fname = input('Enter file name: ')
try:
    fhand = open(fname)
except FileNotFoundError:
    print('File cannot be opened:', fname)
    exit()

for line in fhand:
    line = line.translate(str.maketrans('', '', string.digits))
    line = line.translate(str.maketrans('', '', string.punctuation))
    line = line.lower()

    # Removes numbers and punctuation then sets all letters to lower case
    words = line.split()
    for word in words:
        for letter in word:
            # Count each letter for relative frequencies
            counts += 1
            if letter not in dictionary_counts:
                dictionary_counts[letter] = 1
            else:
                dictionary_counts[letter] += 1

for key, val in list(dictionary_counts.items()):
    relative_lst.append((val / counts, key))  # Computes the relative frequency

relative_lst.sort(reverse=True)         # Sorts from highest rel freq

for key, val in relative_lst:
    print(key, val)

Enter file name: mbox-short.txt
0.09290243193820177 e
0.08926221523422145 a
0.07680344538820433 i
0.0713345752226001 o
0.06945465110317366 r
0.06921538803342847 t
0.06388323962196435 s
0.05337275477244373 u
0.052774597098080765 c
0.04400731461384649 n
0.04267427751098046 p
0.04163177413566216 m
0.03424879941209646 d
0.03130928169808419 l
0.023789585220378377 h
0.021482405619264094 f
0.019944285885187908 k
0.01938030864935997 b
0.01755165518773606 g
0.017038948609710662 v
0.01638952027754516 j
0.01098901098901099 y
0.010014868490762736 w
0.008237485686941364 x
0.0013330371028660297 z
0.0009741424982482526 q


In [54]:
def addStrings(num1: str, num2: str) -> str:
        res = []

        carry = 0
        p1 = len(num1) - 1
        p2 = len(num2) - 1
        while p1 >= 0 or p2 >= 0:
            x1 = ord(num1[p1]) - ord('0') if p1 >= 0 else 0
            x2 = ord(num2[p2]) - ord('0') if p2 >= 0 else 0
            value = (x1 + x2 + carry) % 10
            carry = (x1 + x2 + carry) // 10
            res.append(value)
            p1 -= 1
            p2 -= 1
        
        if carry:
            res.append(carry)
        
        return ''.join(str(x) for x in res[::-1])

In [55]:
addStrings(num1: str, num2: str)

SyntaxError: invalid syntax (<ipython-input-55-cdc5578c1867>, line 1)

In [56]:
print(ord('0'))

48


In [64]:
p1='023'
print(ord(p1[0]))


48


In [68]:
def new_sum(iterable):
    result = 0
    for val in iterable:
        result += val
    return result

def test_new_sum_list():
    assert new_sum([1, 2, 3]) == 6
    
def test_new_sum_tuple():
    assert new_sum((-1, 2, 3)) == 6
    
if __name__ == "__main__":
    test_new_sum_list()
    test_new_sum_tuple()

AssertionError: 

In [79]:
import pandas as pd
data = pd.DataFrame([[0, 2, 7, 4, 8],
                         [1, 7, 6, 3, 7],
                         [1, 1, "None", 8, 9],
                         [0, 2, 3, "None", 6],
                         [0, 5, 1, 4, 9]], 
                        columns = [f"feature_{i}" if i!=0 
                                  else "class" for i in range(5)])

In [80]:
data

class  feature_1 feature_2 feature_3  feature_4
0      0          2         7         4          8
1      1          7         6         3          7
2      1          1      None         8          9
3      0          2         3      None          6
4      0          5         1         4          9

In [85]:
data.groupby("class")['feature_4'].mean().to_dict()

{0: 7.666666666666667, 1: 8.0}

In [87]:
def recsplit(L, val, out=[[]]):
    if L == []:
        return out
    elif L[0] == val and out[-1] != [] and L[1:].count(val) != len(L[1:]):
        return recsplit(L[1:], val, out + [[]])
    elif L[0] != val and L[0] is not None:
        return recsplit(L[1:], val, out[:-1] + [out[-1] + [L[0]]])
    else:
        return recsplit(L[1:], val, out)

P = [1,2,3,4,5,None,None,6,7,8,None,9,10,11,None]
P1 = [1,2,3,4,56,7,8,9,10,11]  
print("Subs of P by None =", recsplit(P,None))
print("Subs of P1 by x =", recsplit(P1,2))
print("Subs of P1 by None =", recsplit(P1,None))

Subs of P by None = [[1, 2, 3, 4, 5], [6, 7, 8], [9, 10, 11]]
Subs of P1 by x = [[1], [3, 4, 56, 7, 8, 9, 10, 11]]
Subs of P1 by None = [[1, 2, 3, 4, 56, 7, 8, 9, 10, 11]]


In [ ]:
def recsplit(L, val):
    for i in range(len(val)):
        
        

In [96]:
def nDarray(typeOfitem, dimensions):
  depth = 0
  if type(dimensions) == int:
            dimensions = [dimensions]
  return(recursiveAllocator(typeOfitem,dimensions,depth))

# recursive internal function
def recursiveAllocator(basetype, dimensionList, depth):
  
  # Base case
  if depth == len(dimensionList)-1:
    currentDimension = dimensionList[depth]
    array = []
    for i in range(0,currentDimension):
      array.append(basetype())
    return array

  # Recursive case 
  else:
    array=[]
    currentDimension = dimensionList[depth]

    # for each element in each dimension recursivly
    # call the function
    for i in range(0,currentDimension):
      array.append(recursiveAllocator(basetype,dimensionList, depth+1))
    return array

In [97]:
typeOfitem=[1,2,3,5,6,7,8,8,9,9,0,0]
dimensions=[2,3,4]

In [103]:
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        lin.append(i)
        
lst=[1,5,6,48]
n=2
list(chunks(range(10, 75), 10))


[range(10, 20),
 range(20, 30),
 range(30, 40),
 range(40, 50),
 range(50, 60),
 range(60, 70),
 range(70, 75)]

In [119]:
a=[1,2,3,4,5,6,7,8,8,9,10,11,12,13,14,34]
n=5
k, m = divmod(len(a), n)
print(len(a),k,m)
if m==0:
    print([a[i:i+n] for i in range(0,len(a),n)])
else:
    for i in range(n-m):
        a.append(0)
    print([a[i:i+n] for i in range(0,len(a),n)])

16 3 1
[[1, 2, 3, 4, 5], [6, 7, 8, 8, 9], [10, 11, 12, 13, 14], [34, 0, 0, 0, 0]]


In [ ]:
class Stack:
    def __init__(self):
        self.stack=[]
    def append(self,x):
        if x not in self.stack:
            self.stack.append(x)
            return True
        else:
            return False
    def pop(self):
        return self.stack[-1]
        
        

In [128]:
class Solution:
    def buildArray(self, target, n):
        ans = []
        move = 0
        for i in range(1, n+1):
            ans.append("Push")
            move += 1
            if i not in target:
                ans.append("Pop")
                move -= 1
            if move == len(target):
                break
        return ans

In [132]:
if __name__ == "__main__":
    s=Solution()
    l=s.buildArray([1,3,5,4,6,8],6)
    print(l)


['Push', 'Push', 'Pop', 'Push', 'Push', 'Push', 'Push']


In [144]:
print (sum(ord(c) for c in 'Jado&'))

420


In [145]:
def ArrayRotation(arr):
  pos = arr[0]

  arr1 = arr[:pos]
  arr2 = arr[pos:]

  str_arr = ''

  for i in arr2:
    str_arr += str(i)

  for i in arr1:
    str_arr += str(i)

  return str_arr


print(ArrayRotation(input()))


1,2,3,4


TypeError: slice indices must be integers or None or have an __index__ method

In [ ]:
ArrayRotation([3,4,5,76])

In [146]:
if __name__ == '__main__':
    T = int(input())
    for _ in range(T):
        s = input()
        v = ['a','e','i','o','u','A','E','I','O','U']
        c = 0
        for i in s:
            if i in v:
                c += 1
        print(c)

dcdsdv


ValueError: invalid literal for int() with base 10: 'dcdsdv'

In [149]:
vowels=['a','e','i','o','u']
data=input()
count=0
for i in data:
    for j in vowels:
        if i.lower()==j:
            count=-count+1
print(count)
        

fvfwer
1


In [159]:
def toLowerCase(value):
        upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        lower = "abcdefghijklmnopqrstuvwxyz"
        h = dict(zip(upper, lower))
        
        return ''.join([h[x] if x in h else x for x in value])
value="MADHAVI NAMBALLA "
print(toLowerCase(value))


madhavi namballa 


In [ ]:
def LetterChanges(strParam):

  # code goes here
  new_str=""
  vowels=['a','e','i','o','u']
  for i in strParam:
    if i.isalpha():
      temp=ord(i)+1
      temp=chr(temp)
      if temp in vowels:
        new_str+=temp.upper()
      else:
        new_str+=temp
    else:
      new_str+=i

  return new_str

# keep this function call here 
print(LetterChanges(input()))

In [161]:
value="madhavi namballa"
lower='abcdefghijklmnopqrstuvwxyz'
upper='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
h=dict(zip(lower,upper))
out=''.join([h[x] if x in h else x for x in value])
print(out)

MADHAVI NAMBALLA


In [165]:
def LetterChange(value):
    vowels=['a','e','i','o','u']
    new_str=""
    for i in value:
        if i.isalpha():
            temp=ord(i)+1
            temp=chr(temp)
            if temp in vowels:
                new_str=new_str+temp.upper()
            else:
                new_str=new_str+temp
    return new_str
value="madhvi namballa"
print(LetterChange(value))

nbEIwjObncbmmb


In [ ]:
punctuation='!?,.:;"\')(_-&'
def retrive_punc(sen):
  newstr=''
  for i in sen:
    if i not in punctuation:
      newstr+=i
  return newstr


def LongestWord(sen):
    word=sen.split(" ")
    new_str=""
    for i in word:
      if len(i)>len(new_str):
        new_str=i


  # code goes here
    return new_str

# keep this function call here 
print(LongestWord(retrive_punc(input())))

In [166]:
punctuation='?!,.:"\')(_-&'
def pun(sen):
    new_str=""
    for i in sen:
        if i not in punctuation:
            new_str+=i
    return new_str
print(pun("hsrfhwiurfwr&kdrugh:"))

hsrfhwiurfwrkdrugh


In [170]:
def longestword(sen):
    new_word=''
    words=sen.split(" ")
    for word in words:
        if len(word)>len(new_word) and word==new_word:
            new_word=word
        elif len(word)>len(new_word):
            new_word=word
    return new_word
print(longestword("madhavia namballa is ver great "))        

madhavia


In [ ]:
def SecondGreatLow(arr):
  arr.sort()
  modified_arr=[]
  for number in arr:
    if number not in modified_arr:
      modified_arr.append(number)
  if len(modified_arr)>2:
     return "{} {}".format(modified_arr[1], modified_arr[-2])
  elif len(modified_arr)==2:
     return "{} {}".format(modified_arr[1], modified_arr[0])
  elif len(modified_arr)==1:
     return "{} {}".format(modified_arr[0], modified_arr[0])

# keep this function call here 
print(SecondGreatLow(input()))

In [172]:
print(121//10)

12


In [173]:
print(divmod(121,10))

(12, 1)


In [ ]:
coeffient,rem=divmod(121,10)

In [193]:
def palindrome_check(number):
    reverse=0
    original=number
    while number>0:
        rem=number%10
        reverse=reverse*10+rem
        number=number//10
    if reverse==original:
        return True
    else:
        return False
print(palindrome_check(-121))

False


In [184]:
def palindrome_check(number):
    original=number
    reverse=0
    while(number>0):
        rem=number%10
        reverse=reverse*10+rem
        number=number//10
    if original==reverse:
        return True
    else:
        return False
print(palindrome_check(535))

True


In [189]:
def isPalindrome(s):
        s=s.lower()
        rev_str=s[::-1]
        if s==rev_str:
            return True
        else:
            return False


In [192]:
print(isPalindrome('lil'))

True


In [240]:
from collections import Counter
def longestPalindrome(s):
    ans = 0
    sem=dict(Counter(s))
    for v in sem.values():
#         print(v)
        ans += v / 2 * 2
        if ans % 2 == 0 and v % 2 == 1:
            ans += 1
    return ans
        

#     for v in sem.items():
#         ans += v / 2 * 2
#         if ans % 2 == 0 and v % 2 == 1:
#             ans += 1
#     return ans

In [241]:
s = "abccccdd"
print(longestPalindrome(s))
#s="bb"

9.0


In [216]:
from collections import Counter
s="abccccdd"
sem=Counter(s)
print(sem.items())
print(sem)
for i in sem.items():
    print(type(i))

dict_items([('a', 1), ('b', 1), ('c', 4), ('d', 2)])
Counter({'c': 4, 'd': 2, 'a': 1, 'b': 1})
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [242]:
l='123'
p=len(s)-1
print(ord(l[p]))

IndexError: string index out of range

In [244]:
num1='123'
p1 = len(num1) - 1
x1 = ord(num1[p1])
print(x1)

51


In [246]:
print(ord('0'))

48


In [248]:
def rotate(arr, n): 
    x = arr[n - 1] 
      
    for i in range(n - 1, 0, -1): 
        arr[i] = arr[i - 1]; 
          
    arr[0] = x; 
  
  
# Driver function 
arr= [1, 2, 3, 4, 5] 
n = len(arr) 
print ("Given array is") 
for i in range(0, n): 
    print (arr[i], end = ' ') 
  
rotate(arr, 3) 
  
print ("\nRotated array is") 
for i in range(0, n): 
    print (arr[i], end = ' ') 
  
# This article is contributed  
# by saloni1297 

Given array is
1 2 3 4 5 
Rotated array is
3 1 2 4 5 

In [252]:
s="m1a2d3h4a5v6i"
alpha = [c for c in s if c.isalpha()] # stack of alphabets
print(alpha)
digit = [c for c in s if c.isdigit()] # stack of digits
print(digit)
        
if abs(len(alpha) - len(digit)) > 1:
    print("not possible")# impossible
if len(alpha) < len(digit): 
    alpha, digit = digit, alpha # alpha >= digit 
        return "".join(a+d for a, d in zip_longest(alpha, digit, fillvalue=""))

['m', 'a', 'd', 'h', 'a', 'v', 'i']
['1', '2', '3', '4', '5', '6']


In [263]:
from itertools import zip_longest 
alpha = [c for c in s if c.isalpha()] # stack of alphabets
digit = [c for c in s if c.isdigit()] # stack of digits
print(dict(zip_longest(alpha, digit, fillvalue="")))

{'m': '1', 'a': '5', 'd': '3', 'h': '4', 'v': '6', 'i': ''}


In [303]:
st="10b1c2"
alpha=[c for c in st if c.isalpha()]
digit=[c for c in st if c.isdigit()]
print(len(alpha))
print(len(digit))
sample=dict(zip_longest(alpha,digit,fillvalue=""))
print(abs(len(alpha) - len(digit)))

2
4
2


In [270]:
upper='ABCDEFGHIJKLMNOPQRSTUVW'
lower='abcdefghijklmnopqrstuvwxyz'
print(dict(zip(lower,upper)))

{'a': 'A', 'b': 'B', 'c': 'C', 'd': 'D', 'e': 'E', 'f': 'F', 'g': 'G', 'h': 'H', 'i': 'I', 'j': 'J', 'k': 'K', 'l': 'L', 'm': 'M', 'n': 'N', 'o': 'O', 'p': 'P', 'q': 'Q', 'r': 'R', 's': 'S', 't': 'T', 'u': 'U', 'v': 'V', 'w': 'W'}


In [311]:
def reformat(s):
        alpha = [c for c in s if c.isalpha()] # stack of alphabets
        digit = [c for c in s if c.isdigit()] # stack of digits
        
        if abs(len(alpha) - len(digit)) > 1: 
            return "7iut" # impossible
        
        if len(alpha) < len(digit): 
            alpha, digit = digit, alpha # alpha >= digit 
        return "".join(a+d for a, d in zip_longest(alpha, digit, fillvalue=""))

In [313]:
st="covid2019"
print(reformat(st))

c2o0v1i9d


In [317]:
a={
    "brand":"Ford",
    "model":"Mustang",
    "year":1994
}

In [326]:
for x,y in a.items():
    print(x,y)

brand Ford
model Mustang
year 1994


In [337]:
nums = [11,7,11,2]
target = 9
h={}
for i, num in enumerate(nums):
#     print(i,num)
    n = target - num
    if n not in h:
        h[num]=i
        print(h)
    else:
        print ([h[n],i])
        
#     print(n)

{11: 0}
{11: 0, 7: 1}
{11: 2, 7: 1}
[1, 3]


In [344]:
import yaml

with open(r'fruits.yaml') as file:
    # The FullLoader parameter handles the conversion from YAML
    # scalar values to Python the dictionary format
    fruits_list = yaml.load(file, Loader=yaml.FullLoader)
    

    print(fruits_list)

{'apples': 20, 'mangoes': 2, 'bananas': 3, 'grapes': 100, 'pineapples': 1}


In [345]:
with open(r'categories.yaml') as file:
    documents = yaml.full_load(file)


In [346]:
for item,doc in documents.items():
    print(item, ":", doc)

sports : ['soccer', 'football', 'basketball', 'cricket', 'hockey', 'table tennis']
countries : ['Pakistan', 'USA', 'India', 'China', 'Germany', 'France', 'Spain']


In [349]:
dict_file = [{'sports' : ['soccer', 'football', 'basketball', 'cricket', 'hockey', 'table tennis']},
{'countries' : ['Pakistan', 'USA', 'India', 'China', 'Germany', 'France', 'Spain']}]

with open(r'store_file.yaml', 'w') as file:
    documents = yaml.dump(dict_file, file)

In [350]:
with open(r'store_file.yaml', 'w') as file:
    documents = yaml.load(store_file, file)
    print(documents)

NameError: name 'store_file' is not defined

In [ ]:
Job Description :-
•             5 – 8+ years professional experience.
•             Experience building and managing microservice architecture based application using Python (Python3 preferred).
•             Experience with python packages like numpy, pandas, flask, pyspark, pymongo, os, logging, re, pyyaml.
•             Experience with swagger io module to expose API
•             Experience in any of: OpenShift, Kubernetes, NGINX, or Docker a plus.
•             Strong RDBMS and Unix understanding with SQL and BASH shell scripting knowledge.
•             Experience with Big Data products like Hadoop, Hive will be a plus
 
Competencies:
         
•             Independent contributor.
•             Self-Driven and result oriented.
•             Verbal and Written communication skills - primarily the ability to communicate ideas, standards and technical details to the development partners.
•             Ability to work effectively within cross functional teams.
•             Strong understanding of technology concepts and best practices.

In [355]:
import numpy as np
x = np.random.random((3,3,3))
print(x)
max_value = np.max(x)
min_value = np.min(x)
print('Maximum value of the array is',max_value)
print('Minimum value of the array is',min_value)

[[[0.81468145 0.37517593 0.50456283]
  [0.69463295 0.48124015 0.36945437]
  [0.13646352 0.44760012 0.44313328]]

 [[0.07739667 0.08836558 0.03966288]
  [0.42655978 0.24402248 0.37042451]
  [0.3158586  0.90819089 0.49439457]]

 [[0.84866459 0.9284673  0.01227487]
  [0.89057536 0.99190277 0.8695499 ]
  [0.04518396 0.07873806 0.24564836]]]
Maximum value of the array is 0.991902770544191
Minimum value of the array is 0.012274866099942439


In [356]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.04401333 0.1278477  0.21889103 0.2756473 ]
 [0.26273021 0.88747458 0.25400447 0.14257475]
 [0.5157038  0.54082752 0.27046972 0.00106136]
 [0.94987131 0.49931738 0.22073419 0.14876764]
 [0.96105102 0.53179543 0.75797325 0.37238553]
 [0.37327006 0.98997703 0.16076955 0.99259885]
 [0.50532729 0.54556727 0.22667865 0.35690387]
 [0.15559189 0.86231399 0.23432696 0.48430405]
 [0.42285281 0.04273016 0.17011897 0.77312481]
 [0.51524748 0.94087598 0.91206426 0.83397634]]
First 5 rows of the above array:
[[0.04401333 0.1278477  0.21889103 0.2756473 ]
 [0.26273021 0.88747458 0.25400447 0.14257475]
 [0.5157038  0.54082752 0.27046972 0.00106136]
 [0.94987131 0.49931738 0.22073419 0.14876764]
 [0.96105102 0.53179543 0.75797325 0.37238553]]
